opt:
  - name: SGD
    params:
    kwargs:
      lr: 0.1
      weight_decay: 0.0001
      momentum: 0.9
      nesterov: True
    scheduler_on_epoch:
      name: CosineAnnealingLR
      kwargs:
        T_max: ${experience.max_iter}
        eta_min: 0.000001
        last_epoch: -1
    scheduler_on_step:
    scheduler_on_val:
