opt:
  - name: Adam
    params: backbone
    kwargs:
      lr: 0.00001
      weight_decay: 0.0004
    scheduler_on_epoch:
      name: CosineAnnealingLR
      kwargs:
        T_max: ${experience.max_iter}
        eta_min: 0.000001
        last_epoch: -1
    scheduler_on_step:
    scheduler_on_val:

  - name: Adam
    params: fc
    kwargs:
      lr: ${mult:2,${optimizer.opt.0.kwargs.lr}}
      weight_decay: ${optimizer.opt.0.kwargs.weight_decay}
    scheduler_on_epoch: ${optimizer.opt.0.scheduler_on_epoch}
    scheduler_on_step:
    scheduler_on_val:
