name: ${loss.losses.0.name}
losses:
  - name: CSLLoss
    weight: 1.0
    kwargs:
      num_proxies: ${dataset.num_classes_train_level0}
      margins: [0.25, 0.45]
      scale: 32
      embedding_size: ${model.kwargs.embed_dim}
      reduce_type: sum
    optimizer:
      name: Adam
      params:
      kwargs:
        lr: 10.0
        weight_decay: 0.0
      scheduler_on_epoch: ${optimizer.opt.0.scheduler_on_epoch}
      scheduler_on_step:
      scheduler_on_val:
