name: iNaturalist18Dataset

num_classes_train_level0: 5690
num_classes_train_level1: 13

num_samples_train: 325846

kwargs:
  data_dir: /local/DEEPLEARNING/image_retrieval/Inaturalist
  alpha: 1.0
  relevance_type: pop
  hierarchy_mode: base

sampler:
  name: MPerClassSampler
  kwargs:
    batch_size: 256
    samples_per_class: 4
